spring:
  application:
    name: auth-server

  cloud:
    openfeign:
      client:
        config:
          keycloak-server:
            url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

keycloak:
  realm: ${KEYCLOAK_REALM:p2f}
  client-id-admin: ${KEYCLOAK_CLIENT_ID_ADMIN:admin-cli}
  client-id-user: ${KEYCLOAK_CLIENT_ID_USER:auth-serv}
  client-secret-user: ${KEYCLOAK_CLIENT_SECRET_USER:6e7o0JqXu4ld2dkCNHcfCSwpkAxsTFKw}
  admin-username: ${KC_BOOTSTRAP_ADMIN_USERNAME:admin}
  admin-password: ${KC_BOOTSTRAP_ADMIN_PASSWORD:admin}
  grant-type: ${KEYCLOAK_GRANT_TYPE:password}
  refresh-grant-type: ${KEYCLOAK_REFRESH_GRANT_TYPE:refresh_token}

server:
  port: 3334