spring:
  application:
    name: movie-microservice

  data:
    elasticsearch:
      cluster-nodes: ${ELASTICSEARCH_URL:localhost:9200}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:8080/realms/p2f}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
  port: 3332

elastic:
  username: ${ELASTICSEARCH_USERNAME:elast}
  password: ${ELASTICSEARCH_PASSWORD:password}