spring:
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761